# Setup folders
- name: create parent deploy dir
  ansible.builtin.file:
    path: "{{ deploy_dir }}"
    state: directory
    mode: "0755"

- name: Check if release_dir exists
  stat:
    path: "{{ release_dir }}"
  register: release_dir_check

- name: remove release dir if exists
  ansible.builtin.file:
    path: "{{ release_dir }}"
    state: absent
  when: release_dir_check.stat.exists

- name: create release dir
  ansible.builtin.file:
    path: "{{ release_dir }}"
    state: directory
    mode: "0755"
