# get code via githup, clean it
- name: clone github repository
  ansible.builtin.git:
    repo: "{{ repository_url }}"
    dest: "{{ release_dir }}"
    accept_hostkey: true
    single_branch: true
    force: true
    depth: 1
    version: "{{ repository_branch }}"
#  register: git_result

- name: cleanup dev files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ release_dir }}/.git"
    - "{{ release_dir }}/.gitignore"
    - "{{ release_dir }}/.github"
    - "{{ release_dir }}/.php-cs-fixer.php"
    - "{{ release_dir }}/.phpstan.neon"
