# handle shared files and folders
- name: Link shared files
  ansible.builtin.file:
    src: "{{ shared_dir }}/{{ item }}"
    dest: "{{ release_dir }}/{{ item }}"
    state: link
    force: true
  loop: "{{ shared_files_and_dirs | flatten }}"
