# handle shared files and folders
- name: Link shared files and directories
  ansible.builtin.file:
    src: "{{ sv_syd_shared_dir }}/{{ item }}"
    dest: "{{ sv_syd_release_dir }}/{{ item }}"
    state: link
    force: true
  loop: "{{ (sv_syd_shared_files | flatten) + (sv_syd_shared_dirs | flatten) }}"
