# install the app (create softlink)
- name: Publish app
  ansible.builtin.file:
    src: "{{ sv_syd_release_dir }}"
    dest: "{{ sv_syd_current_dir }}"
    state: link
    force: true

- name: Set install to done (only cleanup jobs remaining, errors don't execute a rollback)
  ansible.builtin.set_fact: sv_syd_install_done=true

