- name: Install app
  block:
    # - name: i force a failure
    #   command: /bin/false

#    - include_tasks: 10-setup.yml
#    - include_tasks: 20-update-code.yml
#    - include_tasks: 30-shared-files.yml
    - include_tasks: 40-install_dependencies.yaml

    - name: run 'before optimizing' scripts
      ansible.builtin.shell:
        chdir: "{{ release_dir }}"
        cmd: "{{ item }}"
      when: commands_before_optimizing is defined and commands_before_optimizing!=None
      with_items: "{{ commands_before_optimizing | default([]) }}"

    - meta: end_play

    - name: Warmup cache
      ansible.builtin.shell:
        chdir: "{{ release_dir }}"
        cmd: "{{ console_bin }} cache:warmup"

    - name: Publish app
      ansible.builtin.file:
        src: "{{ release_dir }}"
        dest: "{{ current_dir }}"
        state: link
        force: true

    - ansible.builtin.set_fact: install_done=true

    - debug:
        msg: "Hier"
      when: install_done

    - name: run 'before finishing deploy' scripts
      ansible.builtin.shell:
        chdir: "{{ release_dir }}"
        cmd: "{{ item }}"
      when: commands_before_finishing_deploy is defined and commands_before_finishing_deploy!=None
      with_items: "{{ commands_before_finishing_deploy | default([]) }}"

  rescue:
    - debug:
        msg: 'Error in "{{ ansible_failed_task.name }}" - installation rollbacked.'
